list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_avs36",	title = "DOD_AVS-36" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_bren",	title = "DOD_Bren Light Machine Gun" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_carlgustaf",	title = "DOD_Carl Gustav M/45" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_de_lisle",	title = "DOD_De Lisle Commando Carbine" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_de_lisle_s",	title = "DOD_De Lisle Commando Carbine (Scoped)" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_dp",	title = "DOD_DP-28" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_fg42",	title = "DOD_FG-42" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_gewehr43",	title = "DOD_Gewehr 43" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_kar98k",	title = "DOD_Kar98k" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_kar98k_s",	title = "DOD_Kar98k (Scoped)" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_enfield_4",	title = "DOD_Lee Enfield No.4" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_bar",	title = "DOD_M1918 Browning Automatic Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_30cal",	title = "DOD_M1919 Browning Machine Gun" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_thompson",	title = "DOD_M1A1 Thompson" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_m1carbine",	title = "DOD_M1 Carbine" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_m1garand",	title = "DOD_M1 Garand" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_m3",	title = "DOD_M3" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_mg34",	title = "DOD_MG-34" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_mg42",	title = "DOD_MG-42" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_moisin",	title = "DOD_Mosin Nagant" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_moisin_s",	title = "DOD_Mosin Nagant (Scoped)" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_mp40",	title = "DOD_MP-40" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_mp41",	title = "DOD_MP-41" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_pps43",	title = "DOD_PPS-43" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_ppsh41",	title = "DOD_PPSH-41" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_spring_s",	title = "DOD_Springfield (Scoped)" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_stenmk3",	title = "DOD_Sten MK III" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_svt40",	title = "DOD_SVT-40" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_mp44",	title = "DOD_STG-44" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_thompson1921",	title = "DOD_Thompson 1921" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_T38",	title = "DOD_Type 38 Arisaka" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_t38_s",	title = "DOD_Type 38 Arisaka (Scoped)" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_T100",	title = "DOD_Type 100" }  )
list.Add( "NPCUsableWeapons", { class = "npc_dod_weapon_752_Winchester",	title = "DOD_Winchester Model 1912" }  )
