--// File Generated By Fox-Warrior's Resources Generator Version 2.06 \\--

if (SERVER) then
  resource.AddSingleFile( "materials/VGUI/ttt/doctor_jew_shieldgun.vmt" )
  resource.AddSingleFile( "materials/VGUI/ttt/doctor_jew_shieldgun.vtf" )
end
